// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzbvytojkgyunucraaxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6YnZ5dG9qa2d5dW51Y3JhYXhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyNzgxNDcsImV4cCI6MjA1MTg1NDE0N30.0T5wKwBUb119J6XU4oXVwtewEjwPO36filSVIwoFp7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);